runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Yarn2 Cache and node_modules
      uses: actions/cache@v3
      with:
        path: |
          ./.yarn/cache
          ./.yarn/unplugged
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-node-16-yarn3-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-16-yarn3-

    - run: yarn install --immutable
      shell: bash

    - run: yarn wss contracts
      shell: bash
