cloneConcurrency: 8

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.4.1.cjs
