#!/usr/bin/env bash

# Bash sets the BASH environment variable, so if it is not set, then we
# are running in a different shell, so manually run ourselves in BASH.
if [ -z "${BASH:-}" ]; then
  exec bash "$0" "$@"
fi

source "$(dirname "$0")/_/husky.sh"

set -euo pipefail

npx lint-staged

# Run the full tsc for chagned packages, since tsc doesn't play well with lint-staged.
pids=()

# For each package:
for package in contracts sdk; do
  # Check if the package has any staged changes.
  if ! git diff --exit-code --staged packages/$package 1> /dev/null; then
    # Run tsc for that package in a thread.
    echo "type checking $package" && yarn workspace $package lint:tsc &
    # Use remember the pid to wait for it to finish.
    pids+=($!)
  fi
done

# Check that all threads succeeded.
for pid in ${pids[@]+"${pids[@]}"}; do
  wait "$pid"
done
