runs:
  using: "composite"
  steps:
    - name: Start blockchain
      run: yarn ws contracts start &
      shell: bash

    - name: Serve test indexer
      run: yarn ws indexer e2e:serve
      shell: bash

    # TODO: use https://www.npmjs.com/package/start-server-and-test
    - name: wait for services
      run: sleep 20s
      shell: bash

    # Run e2e test once services are started
    - name: E2E Tests
      run: yarn ws e2e e2e:test
      shell: bash
