name: indexer-cron
on:
  schedule:
    # Every hour
    - cron: "0 */1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Staging
        run: |
          curl --request POST \
          --url 'https://gsr-network-staging.vercel.app/api/sync' \
