name: Deploy to prod from main
"on":
  push:
    branches:
      - main
env:
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/gsr?schema=public"
  NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  NEXT_PUBLIC_INFURA_ID: ${{ secrets.INFURA_ID }}
  NEXT_PUBLIC_GSR_CHAIN_ID: 80001
  NEXT_PUBLIC_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
  NEXT_PUBLIC_MAPBOX_STYLE_URL: ${{ secrets.MAPBOX_STYLE_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      # Set up postgres
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Check out code"
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: yarn build
      - run: yarn lint
      - run: yarn test

      - name: Apply DB Migrations
        run: yarn ws indexer prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_MIGRATE_URL }}

      # ===
      # E2E Test
      # ===

      # Start local blockchai
      # - name: Start blockchain
      #   run: yarn ws contracts start &

      # # Start indexer
      # - name: Start indexer
      #   run: yarn ws indexer start &
      #   env:
      #     DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/gsr?schema=public"
      #     GSR_CHAIN_ID: 1337

      # - name: wait for services
      #   run: sleep 20s

      # # Run e2e test once services are started
      # - name: E2E Tests
      #   run: yarn ws e2e test:e2e

      - name: Pull Vercel Environment Information
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
