name: Check PR
"on": pull_request

jobs:
  set-up-repo:
    runs-on: ubuntu-20.04
    services:
      # Set up postgres
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Check out code"
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: yarn build
      - run: yarn lint
      - name: Unit Tests
        run: yarn test

      # ===
      # E2E Test
      # ===

      # Start local blockchain
      - name: Start blockchain
        run: yarn ws contracts start & wait-on http://locahost:8545

      # Start indexer
      - name: Start indexer
        run: yarn ws indexer start & wait-on http://locahost:3000
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/gsr?schema=public"
          GSR_CHAIN_ID: 1337

      # Run e2e test
      - name: E2E Tests
        run: yarn ws e2e test:e2e
