name: Check PR
"on": pull_request

jobs:
  set-up-repo:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out code"
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: yarn build
      - run: yarn lint
      - run: yarn test

      # TODO: Start services in background and wait for them to be ready
      # - run: yarn ws contracts start
      # - run: yarn ws indexer start
      # - run: yarn ws e2e test:e2e
