name: Check PR
"on": pull_request

jobs:
  set-up-repo:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out code"
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: yarn build
      - run: yarn lint
      - run: yarn test

      - yarn ws contracts blockchain
      - yarn ws indexer start
      - yarn ws e2e test
