name: Check PR
"on": pull_request
env:
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/gsr?schema=public"
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      # Set up postgres
      postgres:
        # Docker Hub image
        image: postgres
        env:
          # E2E port
          PGPORT: 5433
          # Provide the password for postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Check out code"
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: NODE_ENV=test yarn build
      - run: yarn lint
      - run: yarn test

      - name: E2E Tests
        uses: ./.github/actions/e2e

      - name: Deploy Indexer
        uses: ./.github/actions/vercel
        with:
          environment: preview
          token: ${{ secrets.VERCEL_TOKEN }}
