name: Deploy to staging from develop
"on":
  push:
    branches:
      - develop
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    services:
      # Set up db
      cockroach:
        image: timveil/cockroachdb-single-node:latest
        env:
          DATABASE_NAME: gsr
          MEMORY_SIZE: 640MiB
        ports:
          - 26258:26257
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: Setup Deps
        uses: ./.github/actions/setup

      - run: NODE_ENV=test yarn build
      - run: yarn lint
      - run: yarn test

      - name: E2E Tests
        uses: ./.github/actions/e2e

      - name: Apply DB Migrations
        run: yarn ws indexer prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.STAGING_MIGRATE_URL }}

      - name: Deploy Indexer
        uses: ./.github/actions/vercel
        with:
          environment: preview
          token: ${{ secrets.VERCEL_TOKEN }}
